// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: metadatav1/metadata.proto

package metadatav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_metadatav1_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metadatav1_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_metadatav1_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *GetMetadataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataResponse) Reset() {
	*x = GetMetadataResponse{}
	mi := &file_metadatav1_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataResponse) ProtoMessage() {}

func (x *GetMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metadatav1_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetMetadataResponse) Descriptor() ([]byte, []int) {
	return file_metadatav1_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *GetMetadataResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMetadataResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetMetadataResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PutMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutMetadataRequest) Reset() {
	*x = PutMetadataRequest{}
	mi := &file_metadatav1_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutMetadataRequest) ProtoMessage() {}

func (x *PutMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metadatav1_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutMetadataRequest.ProtoReflect.Descriptor instead.
func (*PutMetadataRequest) Descriptor() ([]byte, []int) {
	return file_metadatav1_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *PutMetadataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PutMetadataRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PutMetadataRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PutMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutMetadataResponse) Reset() {
	*x = PutMetadataResponse{}
	mi := &file_metadatav1_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutMetadataResponse) ProtoMessage() {}

func (x *PutMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metadatav1_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutMetadataResponse.ProtoReflect.Descriptor instead.
func (*PutMetadataResponse) Descriptor() ([]byte, []int) {
	return file_metadatav1_metadata_proto_rawDescGZIP(), []int{3}
}

var File_metadatav1_metadata_proto protoreflect.FileDescriptor

const file_metadatav1_metadata_proto_rawDesc = "" +
	"\n" +
	"\x19metadatav1/metadata.proto\x12\vmetadata.v1\"$\n" +
	"\x12GetMetadataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"]\n" +
	"\x13GetMetadataResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\\\n" +
	"\x12PutMetadataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x15\n" +
	"\x13PutMetadataResponse2\xb5\x01\n" +
	"\x0fMetadataService\x12P\n" +
	"\vGetMetadata\x12\x1f.metadata.v1.GetMetadataRequest\x1a .metadata.v1.GetMetadataResponse\x12P\n" +
	"\vPutMetadata\x12\x1f.metadata.v1.PutMetadataRequest\x1a .metadata.v1.PutMetadataResponseB*Z(authorsbooks/proto/metadatav1;metadatav1b\x06proto3"

var (
	file_metadatav1_metadata_proto_rawDescOnce sync.Once
	file_metadatav1_metadata_proto_rawDescData []byte
)

func file_metadatav1_metadata_proto_rawDescGZIP() []byte {
	file_metadatav1_metadata_proto_rawDescOnce.Do(func() {
		file_metadatav1_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metadatav1_metadata_proto_rawDesc), len(file_metadatav1_metadata_proto_rawDesc)))
	})
	return file_metadatav1_metadata_proto_rawDescData
}

var file_metadatav1_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_metadatav1_metadata_proto_goTypes = []any{
	(*GetMetadataRequest)(nil),  // 0: metadata.v1.GetMetadataRequest
	(*GetMetadataResponse)(nil), // 1: metadata.v1.GetMetadataResponse
	(*PutMetadataRequest)(nil),  // 2: metadata.v1.PutMetadataRequest
	(*PutMetadataResponse)(nil), // 3: metadata.v1.PutMetadataResponse
}
var file_metadatav1_metadata_proto_depIdxs = []int32{
	0, // 0: metadata.v1.MetadataService.GetMetadata:input_type -> metadata.v1.GetMetadataRequest
	2, // 1: metadata.v1.MetadataService.PutMetadata:input_type -> metadata.v1.PutMetadataRequest
	1, // 2: metadata.v1.MetadataService.GetMetadata:output_type -> metadata.v1.GetMetadataResponse
	3, // 3: metadata.v1.MetadataService.PutMetadata:output_type -> metadata.v1.PutMetadataResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_metadatav1_metadata_proto_init() }
func file_metadatav1_metadata_proto_init() {
	if File_metadatav1_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metadatav1_metadata_proto_rawDesc), len(file_metadatav1_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metadatav1_metadata_proto_goTypes,
		DependencyIndexes: file_metadatav1_metadata_proto_depIdxs,
		MessageInfos:      file_metadatav1_metadata_proto_msgTypes,
	}.Build()
	File_metadatav1_metadata_proto = out.File
	file_metadatav1_metadata_proto_goTypes = nil
	file_metadatav1_metadata_proto_depIdxs = nil
}
