// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/authorsv1/authors.proto

package authorsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_proto_authorsv1_authors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorsv1_authors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_proto_authorsv1_authors_proto_rawDescGZIP(), []int{0}
}

func (x *Author) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Genre         string                 `protobuf:"bytes,4,opt,name=genre,proto3" json:"genre,omitempty"`
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_proto_authorsv1_authors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorsv1_authors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_proto_authorsv1_authors_proto_rawDescGZIP(), []int{1}
}

func (x *Book) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Book) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *Book) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type CreateAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuthorRequest) Reset() {
	*x = CreateAuthorRequest{}
	mi := &file_proto_authorsv1_authors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuthorRequest) ProtoMessage() {}

func (x *CreateAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorsv1_authors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuthorRequest.ProtoReflect.Descriptor instead.
func (*CreateAuthorRequest) Descriptor() ([]byte, []int) {
	return file_proto_authorsv1_authors_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAuthorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        *Author                `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuthorResponse) Reset() {
	*x = CreateAuthorResponse{}
	mi := &file_proto_authorsv1_authors_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuthorResponse) ProtoMessage() {}

func (x *CreateAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorsv1_authors_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuthorResponse.ProtoReflect.Descriptor instead.
func (*CreateAuthorResponse) Descriptor() ([]byte, []int) {
	return file_proto_authorsv1_authors_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAuthorResponse) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type GetAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorRequest) Reset() {
	*x = GetAuthorRequest{}
	mi := &file_proto_authorsv1_authors_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorRequest) ProtoMessage() {}

func (x *GetAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorsv1_authors_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorRequest) Descriptor() ([]byte, []int) {
	return file_proto_authorsv1_authors_proto_rawDescGZIP(), []int{4}
}

func (x *GetAuthorRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        *Author                `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Books         []*Book                `protobuf:"bytes,2,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorResponse) Reset() {
	*x = GetAuthorResponse{}
	mi := &file_proto_authorsv1_authors_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorResponse) ProtoMessage() {}

func (x *GetAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorsv1_authors_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorResponse.ProtoReflect.Descriptor instead.
func (*GetAuthorResponse) Descriptor() ([]byte, []int) {
	return file_proto_authorsv1_authors_proto_rawDescGZIP(), []int{5}
}

func (x *GetAuthorResponse) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *GetAuthorResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

type AddBookToAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int64                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Genre         string                 `protobuf:"bytes,4,opt,name=genre,proto3" json:"genre,omitempty"`
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBookToAuthorRequest) Reset() {
	*x = AddBookToAuthorRequest{}
	mi := &file_proto_authorsv1_authors_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBookToAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBookToAuthorRequest) ProtoMessage() {}

func (x *AddBookToAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorsv1_authors_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBookToAuthorRequest.ProtoReflect.Descriptor instead.
func (*AddBookToAuthorRequest) Descriptor() ([]byte, []int) {
	return file_proto_authorsv1_authors_proto_rawDescGZIP(), []int{6}
}

func (x *AddBookToAuthorRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *AddBookToAuthorRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddBookToAuthorRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *AddBookToAuthorRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *AddBookToAuthorRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type AddBookToAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int64                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Books         []*Book                `protobuf:"bytes,3,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBookToAuthorResponse) Reset() {
	*x = AddBookToAuthorResponse{}
	mi := &file_proto_authorsv1_authors_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBookToAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBookToAuthorResponse) ProtoMessage() {}

func (x *AddBookToAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorsv1_authors_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBookToAuthorResponse.ProtoReflect.Descriptor instead.
func (*AddBookToAuthorResponse) Descriptor() ([]byte, []int) {
	return file_proto_authorsv1_authors_proto_rawDescGZIP(), []int{7}
}

func (x *AddBookToAuthorResponse) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *AddBookToAuthorResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddBookToAuthorResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

var File_proto_authorsv1_authors_proto protoreflect.FileDescriptor

const file_proto_authorsv1_authors_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/authorsv1/authors.proto\x12\n" +
	"authors.v1\",\n" +
	"\x06Author\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"r\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x14\n" +
	"\x05genre\x18\x04 \x01(\tR\x05genre\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\")\n" +
	"\x13CreateAuthorRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"B\n" +
	"\x14CreateAuthorResponse\x12*\n" +
	"\x06author\x18\x01 \x01(\v2\x12.authors.v1.AuthorR\x06author\"\"\n" +
	"\x10GetAuthorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"g\n" +
	"\x11GetAuthorResponse\x12*\n" +
	"\x06author\x18\x01 \x01(\v2\x12.authors.v1.AuthorR\x06author\x12&\n" +
	"\x05books\x18\x02 \x03(\v2\x10.authors.v1.BookR\x05books\"\x91\x01\n" +
	"\x16AddBookToAuthorRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x03R\bauthorId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x14\n" +
	"\x05genre\x18\x04 \x01(\tR\x05genre\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\"r\n" +
	"\x17AddBookToAuthorResponse\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x03R\bauthorId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x05books\x18\x03 \x03(\v2\x10.authors.v1.BookR\x05books2\x89\x02\n" +
	"\x0eAuthorsService\x12Q\n" +
	"\fCreateAuthor\x12\x1f.authors.v1.CreateAuthorRequest\x1a .authors.v1.CreateAuthorResponse\x12H\n" +
	"\tGetAuthor\x12\x1c.authors.v1.GetAuthorRequest\x1a\x1d.authors.v1.GetAuthorResponse\x12Z\n" +
	"\x0fAddBookToAuthor\x12\".authors.v1.AddBookToAuthorRequest\x1a#.authors.v1.AddBookToAuthorResponseB(Z&authorsbooks/proto/authorsv1;authorsv1b\x06proto3"

var (
	file_proto_authorsv1_authors_proto_rawDescOnce sync.Once
	file_proto_authorsv1_authors_proto_rawDescData []byte
)

func file_proto_authorsv1_authors_proto_rawDescGZIP() []byte {
	file_proto_authorsv1_authors_proto_rawDescOnce.Do(func() {
		file_proto_authorsv1_authors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_authorsv1_authors_proto_rawDesc), len(file_proto_authorsv1_authors_proto_rawDesc)))
	})
	return file_proto_authorsv1_authors_proto_rawDescData
}

var file_proto_authorsv1_authors_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_authorsv1_authors_proto_goTypes = []any{
	(*Author)(nil),                  // 0: authors.v1.Author
	(*Book)(nil),                    // 1: authors.v1.Book
	(*CreateAuthorRequest)(nil),     // 2: authors.v1.CreateAuthorRequest
	(*CreateAuthorResponse)(nil),    // 3: authors.v1.CreateAuthorResponse
	(*GetAuthorRequest)(nil),        // 4: authors.v1.GetAuthorRequest
	(*GetAuthorResponse)(nil),       // 5: authors.v1.GetAuthorResponse
	(*AddBookToAuthorRequest)(nil),  // 6: authors.v1.AddBookToAuthorRequest
	(*AddBookToAuthorResponse)(nil), // 7: authors.v1.AddBookToAuthorResponse
}
var file_proto_authorsv1_authors_proto_depIdxs = []int32{
	0, // 0: authors.v1.CreateAuthorResponse.author:type_name -> authors.v1.Author
	0, // 1: authors.v1.GetAuthorResponse.author:type_name -> authors.v1.Author
	1, // 2: authors.v1.GetAuthorResponse.books:type_name -> authors.v1.Book
	1, // 3: authors.v1.AddBookToAuthorResponse.books:type_name -> authors.v1.Book
	2, // 4: authors.v1.AuthorsService.CreateAuthor:input_type -> authors.v1.CreateAuthorRequest
	4, // 5: authors.v1.AuthorsService.GetAuthor:input_type -> authors.v1.GetAuthorRequest
	6, // 6: authors.v1.AuthorsService.AddBookToAuthor:input_type -> authors.v1.AddBookToAuthorRequest
	3, // 7: authors.v1.AuthorsService.CreateAuthor:output_type -> authors.v1.CreateAuthorResponse
	5, // 8: authors.v1.AuthorsService.GetAuthor:output_type -> authors.v1.GetAuthorResponse
	7, // 9: authors.v1.AuthorsService.AddBookToAuthor:output_type -> authors.v1.AddBookToAuthorResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_authorsv1_authors_proto_init() }
func file_proto_authorsv1_authors_proto_init() {
	if File_proto_authorsv1_authors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_authorsv1_authors_proto_rawDesc), len(file_proto_authorsv1_authors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_authorsv1_authors_proto_goTypes,
		DependencyIndexes: file_proto_authorsv1_authors_proto_depIdxs,
		MessageInfos:      file_proto_authorsv1_authors_proto_msgTypes,
	}.Build()
	File_proto_authorsv1_authors_proto = out.File
	file_proto_authorsv1_authors_proto_goTypes = nil
	file_proto_authorsv1_authors_proto_depIdxs = nil
}
