// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: booksv1/books.proto

package booksv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Genre         string                 `protobuf:"bytes,4,opt,name=genre,proto3" json:"genre,omitempty"`
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	AuthorId      int64                  `protobuf:"varint,6,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_booksv1_books_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_booksv1_books_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_booksv1_books_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Book) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *Book) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Book) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type AddBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int64                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Genre         string                 `protobuf:"bytes,4,opt,name=genre,proto3" json:"genre,omitempty"`
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBookRequest) Reset() {
	*x = AddBookRequest{}
	mi := &file_booksv1_books_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBookRequest) ProtoMessage() {}

func (x *AddBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booksv1_books_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBookRequest.ProtoReflect.Descriptor instead.
func (*AddBookRequest) Descriptor() ([]byte, []int) {
	return file_booksv1_books_proto_rawDescGZIP(), []int{1}
}

func (x *AddBookRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *AddBookRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddBookRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *AddBookRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *AddBookRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type AddBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*Book                `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"` // lista completa tras crear el libro
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBookResponse) Reset() {
	*x = AddBookResponse{}
	mi := &file_booksv1_books_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBookResponse) ProtoMessage() {}

func (x *AddBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booksv1_books_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBookResponse.ProtoReflect.Descriptor instead.
func (*AddBookResponse) Descriptor() ([]byte, []int) {
	return file_booksv1_books_proto_rawDescGZIP(), []int{2}
}

func (x *AddBookResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

var File_booksv1_books_proto protoreflect.FileDescriptor

const file_booksv1_books_proto_rawDesc = "" +
	"\n" +
	"\x13booksv1/books.proto\x12\bbooks.v1\"\x8f\x01\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x14\n" +
	"\x05genre\x18\x04 \x01(\tR\x05genre\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x12\x1b\n" +
	"\tauthor_id\x18\x06 \x01(\x03R\bauthorId\"\x89\x01\n" +
	"\x0eAddBookRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x03R\bauthorId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x14\n" +
	"\x05genre\x18\x04 \x01(\tR\x05genre\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\"7\n" +
	"\x0fAddBookResponse\x12$\n" +
	"\x05books\x18\x01 \x03(\v2\x0e.books.v1.BookR\x05books2N\n" +
	"\fBooksService\x12>\n" +
	"\aAddBook\x12\x18.books.v1.AddBookRequest\x1a\x19.books.v1.AddBookResponseB$Z\"authorsbooks/proto/booksv1;booksv1b\x06proto3"

var (
	file_booksv1_books_proto_rawDescOnce sync.Once
	file_booksv1_books_proto_rawDescData []byte
)

func file_booksv1_books_proto_rawDescGZIP() []byte {
	file_booksv1_books_proto_rawDescOnce.Do(func() {
		file_booksv1_books_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booksv1_books_proto_rawDesc), len(file_booksv1_books_proto_rawDesc)))
	})
	return file_booksv1_books_proto_rawDescData
}

var file_booksv1_books_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_booksv1_books_proto_goTypes = []any{
	(*Book)(nil),            // 0: books.v1.Book
	(*AddBookRequest)(nil),  // 1: books.v1.AddBookRequest
	(*AddBookResponse)(nil), // 2: books.v1.AddBookResponse
}
var file_booksv1_books_proto_depIdxs = []int32{
	0, // 0: books.v1.AddBookResponse.books:type_name -> books.v1.Book
	1, // 1: books.v1.BooksService.AddBook:input_type -> books.v1.AddBookRequest
	2, // 2: books.v1.BooksService.AddBook:output_type -> books.v1.AddBookResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_booksv1_books_proto_init() }
func file_booksv1_books_proto_init() {
	if File_booksv1_books_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booksv1_books_proto_rawDesc), len(file_booksv1_books_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booksv1_books_proto_goTypes,
		DependencyIndexes: file_booksv1_books_proto_depIdxs,
		MessageInfos:      file_booksv1_books_proto_msgTypes,
	}.Build()
	File_booksv1_books_proto = out.File
	file_booksv1_books_proto_goTypes = nil
	file_booksv1_books_proto_depIdxs = nil
}
